### ISSUE TITLE
Move to more generic shell script shebang

### ISSUE THREAD

**Issue by maartenweyns** [icpctools/icpctools#1002]
All the shell scripts for running the tools currently use the `#!/bin/bash` shebang. While this works on most Linux distributions, it would be nice to move to the `#!/usr/bin/env bash` shebang for a more reliable shebang.

I noticed this while we are looking into moving our custom contest Linux images to NixOS, where `bash` is not present in `/bin`. However, other systems (like OpenBSD or similar) also don't have `bash` in `/bin`.

I am willing to create a PR for this, but wanted to test the waters for the idea first.

**Comment by nickygerritsen** [comment]
I don't think we see any issue with this

**Comment by maartenweyns** [comment]
Cool, I'll make a PR
