### ISSUE TITLE
Redirect old ICPCTools webpage to new GitHub location.

### ISSUE THREAD

**Issue by clevengr** [icpctools/icpctools#306]
I have browser bookmarks for "ICPCTools"; they still point to the old web page -- and there's nothing there that gives any hint that what's there is out of date.  I'm sure there are many other people with similarly outdated bookmarks.  There should at least be a message on the old page pointing to the new page; maybe an automatic redirect?

**Comment by deboer-tim** [comment]
+1 for automatic redirect. But who has access? Troy? I thought maybe you did.

**Comment by deboer-tim** [comment]
The old website has been down for several months now, and as far as I know there is no intention of bring it back up. As much as a redirect might have been nice, I think I'm just going to close this.
