### ISSUE TITLE
Resolver: --speed doesn't appear to work

### ISSUE THREAD

**Issue by gitvanb** [icpctools/icpctools#307]
the command-line parameter --speed doesn't work. Speed can still be adjusted by + and -.

Attached are two files. ok.txt does not use the --speed parameter, not_ok.txt has exactly the same parameters as ok.txt except adding the --speed parameter.

[not_ok.txt](https://github.com/icpctools/icpctools/files/5985049/not_ok.txt)
[ok.txt](https://github.com/icpctools/icpctools/files/5985039/ok.txt)

**Comment by deboer-tim** [comment]
This should be fixed in v2.3.442 and above. @gitvanb are you ok using prerelease build for now (there is very little change in 2.3 so far)? Since this is a regression I'm ok fixing 2.2 as well, but haven't done that yet.

**Comment by gitvanb** [comment]
I can get it to do what I want with the +/- keys, so I'm OK with the current version - unless the prerelease fixes the other issue (iconifying from Display 2)

**Comment by deboer-tim** [comment]
Fixed in the 2.3 release.
