### ISSUE TITLE
Resolver: in Java 14, "Warning: Illegal reflective access"

### ISSUE THREAD

**Issue by ibarland** [icpctools/icpctools#315]
When running with Java 14, I get the warning below.
(This may be known / understood, but thought I'd give a heads-up just in case.)
It of course doesn't happen with Java 8.
It does happen with two different input files.

unix>  resolver-2.0/resolver.sh ian 

--- ICPC Resolver (version 2.0 build 1798) ---
Log: logs/resolver_21.02.27_20.01.46.log
Floor map does not exist
Time to load EF: 1759ms
Resolving 584 pending submissions out of the 1714 total submissions in the contest... 
Done resolving
  Playback time: 16m 15s
  Total pauses: 101
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.acmicpc.presentation.core.internal.PresentationWindowImpl (file:/Users/ibarland/Documents/Service/ICPC/regional-2019/resolver/resolver-2.0/lib/presentCore.jar) to method com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of org.acmicpc.presentation.core.internal.PresentationWindowImpl
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by deboer-tim** [comment]
Hi Ian,
This was fixed in v2.2 (or v2.3 prerelease) via PR #288. You can download newer releases from http://tools.icpc.global. It won't cause any problem in the meantime, but once you move to 2.2+ you won't see the warning anymore.

**Comment by ibarland** [comment]
Thanks for that link (and sorry for the noise.

--Ian
