### ISSUE TITLE
Presentation Client: Misspelling

### ISSUE THREAD

**Issue by gitvanb** [icpctools/icpctools#318]
The word "Judgment" is misspelled as "Judgement" throughout the Presentation Client.

**Comment by nickygerritsen** [comment]
Note that this comes from https://ccs-specs.icpc.io where both spellings are used... We should really use one version, which probably means using `judgement` since otherwise we need to rename the [judgement api](https://ccs-specs.icpc.io/contest_api#judgements) to judgements, which is a total backwards compatible change.

I don't know where the API name came from originally.

**Comment by deboer-tim** [comment]
Where I am this is the both the correct spelling and matches the API. :)

I think the only solution that's going to work is treating this like a translation request and providing an en-US translation.

**Comment by deboer-tim** [comment]
I took an initial look at where 'judgement' appears as an example, and I want to be clear on what I think it reasonable vs priority, etc:
 - I'm the main author of things like documentation and command help, and I'm Canadian so it's going to use judgement and colour more often than not. If this is confusing to anyone they can submit a PR, but I'm not going to spend time making it marginally better for Americans and worse for British, and generally I don't think that's a problem. There are also minor changes often enough that it's not practical to maintain multiple versions.
 - Tools like the presentation admin and CDS are primarily only seen by the same contest admins, who have already had to deal with this spelling. I'm open to translating here, but not a priority.
 - That leaves the end user tools like the presentations, coach view, etc which I think should be translated and pick up the local locale. There is too much work to do in one pass though, so I'd take this in stages based on feedback.

Based on this, I'm going to use this PR to separate strings from all of the scoreboards and 'translate' them to en_US (it looks like there are only a few strings that actually use judgement). Van B, I hope this covers enough of the external/user-facing parts where people would actually notice.

**Comment by deboer-tim** [comment]
Fix is in the 2.3 release.
