### ISSUE TITLE
Mouse click closes resolver

### ISSUE THREAD

**Issue by wmacevoy** [icpctools/icpctools#335]
This is a terrible "feature"
It makes it impossible to regain focus on a second display or zoom.

**Comment by deboer-tim** [comment]
I assume you are on Windows? This is actually 'normal' Windows behaviour for dual monitors, but it was reported in issue #308 and I believe I found a workaround. Could you please try the latest prerelease (v2.3.467 or higher) from https://tools.icpc.global and let me know if it fixes the problem?

**Comment by deboer-tim** [comment]
Fixed in the 2.3 release.
