### ISSUE TITLE
PresAdmin should support hiding Balloon Clients

### ISSUE THREAD

**Issue by clevengr** [icpctools/icpctools#38]
The ability to see and control a Balloon Client in the PresAdmin is arguably useful (at least somewhat...).  However, in the PacNW contest we run six sites, each of which has a Balloon Client and each of which also has one, two, or sometimes as many as three Presentation Clients.  This means we have as many as 24 clients in the "Client window" on the PresAdmin.  This makes it very cluttered and hard to use.    

The reality is that MOST of the time the Balloon Util is not manipulated very much (if at all) by the PresAdmin.  It would be nice if the PresAdmin had an option to "hide" Balloon Client displays in order to reduce the on-screen clutter a bit.

An even better extension would be to make EVERY client display "selectable/hidable".  Maybe for example I only currently want to see the client displays at sites 1 and 3; I'd like to be able to "hide" all the others temporarily.

**Comment by deboer-tim** [comment]
This has been working well for several contests, closing.
