### ISSUE TITLE
PresAdmin password wrongly overwritten in Docker start.sh

### ISSUE THREAD

**Issue by JobDoesburg** [icpctools/icpctools#447]
When setting user passwords via env variables in a the Docker container, the PresAdmin gets wrongly set. More specifically, setting the ADMIN_PASSWORD will also replace the PRES*ADMIN_PASSWORD* by the admin password, before the actual PRESADMIN_PASSWORD is set (as ADMIN_PASSWORD is a substring of PRESADMIN_PASSWORD :p)

This results in the presadmin password being the admin password with `PRES` prepended. So running the Docker container with `-e ADMIN_PASSWORD=myadminpassword -e PRESADMIN_PASSWORD=presadminpassword` will result in presadmin password `PRESmyadminpassword`

The culprit being: https://github.com/icpctools/icpctools/blob/0f4e96a19f100aaebedae62d3b58e46a2f56fe51/build/cds/Docker/start.sh#L5

**Comment by nickygerritsen** [comment]
I’m currently on holiday and after in Moscow for the world finals. Not sure if I can fix it soon but if you want to ahead and do a fix and we will merge it.
