### ISSUE TITLE
Add scoreboard mode to respect freezes on its own

### ISSUE THREAD

**Issue by jsannemo** [icpctools/icpctools#512]
This lets contests run the scoreboard w/o needing a CDS to filter the event feed

**Comment by deboer-tim** [comment]
Hi Johan,
This is now implemented in the 2.5 stream, you just add a param like "--account spectator" to only show what spectators should see. Please give it a try and provide feedback.
Info on what each account type can see is documented here: https://github.com/icpctools/icpctools/blob/main/doc/account-types.md

**Comment by jsannemo** [comment]
Awesome! I'll try to use this for the KTH championships in a few weeks to test
