### ISSUE TITLE
2021 Cleanup

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#580]
New machine and cleaning up my desk - writing down random comments from sticky notes and other docs here so that they don't get lost:

- [ ] Should resolver be chronological by problem?
- [ ]  Resolver should show multiple runs on main scoreboard
- [ ]  Can/should we customize the “CDS” in browser titlebar per page?
- [x]  Balloon printer - option to only give balloons once for identical problem colours (rgb+name)
- [ ]  .bat/.sh should detect if java is installed and give a simple error message
- [ ]  Pres client - prompt for name interactively and remember it

**Comment by niemela** [comment]
> * Should resolver be chronological by problem?

Could you elaborate? I think the answer is "no", but I'm not sure what you mean.

> * Resolver should show multiple runs on main scoreboard

This is now implemented for scoring contests. I don't think it's very useful for pass/fail.

**Comment by deboer-tim** [comment]
> > * Should resolver be chronological by problem?
> 
> Could you elaborate? I think the answer is "no", but I'm not sure what you mean.

Someone had suggested that resolving should start with the first unjudged submission instead of 'left to right', and this would also make it less obvious if we switched the order slightly. It hasn't been suggested since.

> > * Resolver should show multiple runs on main scoreboard
> 
> This is now implemented for scoring contests. I don't think it's very useful for pass/fail.

FWIW this is done on the judge queue, multiple runs are shown as smaller rectangles to the left or right of the last one. It's not useful since it's always 'fail fail fail fail (pass or fail)', but since it is some additional animation and makes the number of submissions more obvious it has been suggested every few years.

**Comment by niemela** [comment]
> Someone had suggested that resolving should start with the first unjudged submission instead of 'left to right', and this would also make it less obvious if we switched the order slightly. It hasn't been suggested since.

It's not a bad idea, it's very logical, but I don't it would make much of a difference. In fact, the biggest difference would probably be that the last submission resolved would now be significantly more likely to be a fail, and that's probably a bad thing?

> FWIW this is done on the judge queue, multiple runs are shown as smaller rectangles to the left or right of the last one. It's not useful since it's always 'fail fail fail fail (pass or fail)', but since it is some additional animation and makes the number of submissions more obvious it has been suggested every few years.

Yeah, it's one of those things that sound like a great idea if you don't really think about it. :)

**Comment by deboer-tim** [comment]
Moved to wiki.
