### ISSUE TITLE
Docker user accounts are incorrect in CDS

### ISSUE THREAD

**Issue by verwoerd** [icpctools/icpctools#625]
For the docker image of cds version 2.5.737 the configuration of the method of user accounts is outdated. It still uses the old `users.xml`, while the cds looks in `accounts.json` as described in the manual. Setting the password through environment variables has currently no effect, since they get inserted in the wrong file.

A work around is to link your own `accounts.json` from the local file system in the docker container to `/opt/wlp/usr/servers/cds/config/accounts.json`.

**Comment by nickygerritsen** [comment]
Ah yeah I will fix this. Probably after SWERC though

**Comment by nickygerritsen** [comment]
Oh you did already…

**Comment by deboer-tim** [comment]
Sorry for the delay. We decided to go with yaml instead of json as the default, so switched the PR. Thanks for the report & PR, they were appreciated, and please let us know if you object to yaml. :)

**Comment by verwoerd** [comment]
No worries, your welcome, and yaml has my preference over json too.
