### ISSUE TITLE
Per-team video configuration does not work

### ISSUE THREAD

**Issue by MarcoUCM** [icpctools/icpctools#628]
When cdsConfig.xml contains a video element for an individual team such as

```
<contest ...>
	 <video
		  id="team01"
		  desktop="http://192.168.10.34:9999"
		  desktopMode="lazy"/>
</contest>
```

 the same configuration is applied to every team (its mapped to different streams in the VideoAggregator).

**Comment by deboer-tim** [comment]
Hi Marco,
Thank you for the bug report and PR! As you know I changed the fix slightly, but this should now be fixed. Please feel free to reopen if you have issues.
