### ISSUE TITLE
Dynamically update file references

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#745]
Today the CDS expects files like backups and logs to be available on startup so that it can immediately/automatically add these to the corresponding contest objects (e.g. teams). This keeps things simple, but backups and logs must be there before the CDS starts (which we've missed before) and if anything changes (e.g. even a backup deleted) the API never reflects this.

We should make the CDS periodically update all file references via a background task, so that new or removed files are updated dynamically (e.g. a target of every 30s).

**Comment by clevengr** [comment]
What happens in a contest that wants to use a CDS but doesn't want to implement the "backup" feature?  (I assume this is talking about the concept that there is some process somewhere that's periodically backing up contestant machines -- and I can easily imagine contests that don't want to do that; we don't do it at the PacNW for example... does that mean we couldn't run a CDS??)

**Comment by deboer-tim** [comment]
I would probably implement this as a background scanner for all file references, since it really doesn't do anything different between logos, backups, or logs today. i.e. the CDS would just do a slow troll of the contest package looking for any changes. You don't need to be using backups, or logos, or anything else, but if you did it would dynamically get picked up if there are changes.

For finals it would mean that if Troy forgot to start the backup script it'd just show up in the feed whenever he did. For PacNW there would be no difference unless something odd happens, e.g. if we had to change a logo we wouldn't need to restart the CDS, we'd just drop/change it in the correct folder and the change would happen.

**Comment by deboer-tim** [comment]
Implemented and tested at WF Astana.
