### ISSUE TITLE
Clock presentation and banner

### ISSUE THREAD

**Issue by MarcoUCM** [icpctools/icpctools#770]
When the contest has a banner, the clock moves upwards. That's a bit strange because the status string remains at the same position:

![1](https://user-images.githubusercontent.com/14042085/231317917-2537810e-7f62-43e3-be9f-4ca5f599195b.png)

The consequence is that the number of switches in the StatusCountdownPresentation that may be used without overlapping is different whether the contest has banner or not.

![2](https://user-images.githubusercontent.com/14042085/231318289-14f09bb7-fcb9-4eb1-b692-ddc0675048ce.png)

That behavior did not occur some months ago. In fact, it seems that it was introduced on #657. 
IMHO the addition to the ClockPresentation.java file should have been done in the PolarCountdownPresentation.java.

**Comment by deboer-tim** [comment]
Fix via PR #781.
