### ISSUE TITLE
Resolver fails with some contest feeds in test mode

### ISSUE THREAD

**Issue by MarcoUCM** [icpctools/icpctools#773]
The console output says that the event fee cannot be loaded and a exception arises:

`--- ICPC Resolver (2.5.904) ---
Log: logs/resolver_23.04.21_10.05.25.log
Couldn't load event feed
   java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
   at org.icpc.tools.contest.model.internal.ContestData.removeFromHistory(ContestData.java:441)
`

I've tracked down the problem and it fails when:

   - There are pending submissions that resolver removes
   - The contest feed contains delete operations, such as the removal of accounts

A minimal event-feed that fails is copy/paste below. It has:

   - A 3 hours contest with just one group, organization, team and account and two problems.
   - An incorrect account that is later removed
   - A correct submission before freeze
   - A correct submission after freeze
   - A pending submission (without judgement) after the contest end

If the incorrect account addition and deletion is removed from the feed, the resolver executes correctly.

`{"type":"contest","id":"3","data":{"id":"3","name":"Test Contest","formal_name":"Test Contest","start_time":"2023-04-19T16:00:00.000+02:00","duration":"3:00:00.000","scoreboard_freeze_duration":"0:45:00.000","penalty_time":20},"token":"cdU0"}
{"type":"judgement-types","id":"AC","data":{"id":"AC","name":"correct","penalty":false,"solved":true},"token":"cdU1"}
{"type":"judgement-types","id":"WA","data":{"id":"WA","name":"wrong answer","penalty":true,"solved":false},"token":"cdU8"}
{"type":"languages","id":"cpp","data":{"id":"cpp","name":"C++","entry_point_required":false,"extensions":["cpp","cc","cxx","c++"]},"token":"cdU10"}
{"type":"problems","id":"1","data":{"id":"1","label":"A","name":"Problem A","ordinal":0,"color":"yellow","rgb":"#FFFF00","test_data_count":1,"time_limit":1},"token":"cdU13"}
{"type":"problems","id":"2","data":{"id":"2","label":"B","name":"Problem B","ordinal":1,"color":"red","rgb":"#FF0000","test_data_count":1,"time_limit":1},"token":"cdU14"}
{"type":"groups","id":"1","data":{"id":"1","name":"Participants"},"token":"cdU16"}
{"type":"organizations","id":"1","data":{"id":"1","icpc_id":"UNI","name":"UNI","formal_name":"University of..."},"token":"cdU677"}
{"type":"teams","id":"1","data":{"id":"1","label":"1","name":"team1","group_ids":["1"],"organization_id":"1"},"token":"cdU22"}
{"type":"accounts","id":"1","data":{"id":"1","name":"wrong_name","username":"wrong_name"},"token":"cdU706"}
{"type":"accounts","id":"1","data":null,"token":"cdU707"}
{"type":"accounts","id":"2","data":{"id":"2","name":"team 1","username":"team1","type":"team", "team_id":"1"},"token":"cdU26"}
{"type":"state","data":{"started":"2023-04-19T16:00:00.000+02:00"},"token":"cdU814"}
{"type":"submissions","id":"1","data":{"id":"1","problem_id":"1","team_id":"1","language_id":"cpp","files":[{"href":"contests/3/submissions/1/files","mime":"application/zip"}],"contest_time":"1:00:00.000","time":"2023-04-19T17:00:00.000+02:00"},"token":"cdU1000"}
{"type":"judgements","id":"1","data":{"id":"1","submission_id":"1","judgement_type_id":"AC","max_run_time":0.002,"start_contest_time":"1:00:13.890","start_time":"2023-04-19T17:00:13.890+02:00"},"token":"cdU1001"}
{"type":"state","data":{"started":"2023-04-19T16:00:00.000+02:00","frozen":"2023-04-19T18:15:00.000+02:00"},"token":"cdU3903"}
{"type":"submissions","id":"2","data":{"id":"2","problem_id":"2","team_id":"1","language_id":"cpp","files":[{"href":"contests/3/submissions/1/files","mime":"application/zip"}],"contest_time":"2:30:00.000","time":"2023-04-19T18:30:00.000+02:00"},"token":"cdU4000"}
{"type":"judgements","id":"2","data":{"id":"2","submission_id":"2","judgement_type_id":"AC","max_run_time":0.002,"start_contest_time":"2:30:13.890","start_time":"2023-04-19T18:30:13.890+02:00"},"token":"cdU4001"}
{"type":"state","data":{"started":"2023-04-19T16:08:00.000+02:00","ended":"2023-04-19T19:00:00.000+02:00","frozen":"2023-04-19T18:15:00.000+02:00"},"token":"cdU5267"}
{"type":"submissions","id":"3","data":{"id":"3","problem_id":"2","team_id":"1","language_id":"cpp","files":[{"href":"contests/3/submissions/1/files","mime":"application/zip"}],"contest_time":"3:05:00.000","time":"2023-04-19T19:05:00.000+02:00"},"token":"cdU5200"}
{"type":"awards","id":"rank-1","data":{"id":"rank-1","team_ids":["1"],"citation":"First position"},"token":"cdU5309"}
`

**Comment by deboer-tim** [comment]
Thank you for the fix and sorry for the slow review! PR merged.
