### ISSUE TITLE
Client ability to connect to contest based on hint

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#815]
Currently, the tools clients can connect to a specific contest (e.g. "http://cds/wf2020") or to the 'current' contest (e.g. "http://cds"). We use the second at World Finals so that we don't need to go around updating multiple machines every day as we switch from test to dress to finals contest.

This won't work in Sharm if we have a single CDS running both contests, since we'll have two of everything. We need hint, regex, or partial name support so that you can say something like "http://cds/[46]" to match whatever the current contest is that includes "46".

**Comment by troy2914** [comment]
why would want a single CDS handling both contests?

**Comment by nickygerritsen** [comment]
Two things I can think of:

* If we want to switch ONE presentation machine between two contests, it's easier if it is the same CDS
* If we want to start two contests at the same time it would be way easier if it is one CDS

**Comment by deboer-tim** [comment]
Yeah, that. The same reason Sam wants one button to pause/start them: only a single thing to configure/admin. :) 

I'm not 100% sure we need this, but it is very easy to implement and unblocks the path if we ever need this.

**Comment by deboer-tim** [comment]
Fixed by PR #825.
