### ISSUE TITLE
Contest state should return {}, not empty response, before any state changes.

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#860]
Currently the contest state endpoint returns an empty response when the contest hasn't started yet. I think it should return `{}`.

**Comment by clevengr** [comment]
I think I disagree that it should return **{}**.    I think it should return (something like):
```json
{
  "started": null,
  "ended": null,
  "frozen": null,
  "thawed": null,
  "finalized": null,
  "end_of_updates": null
}
```
This would be consistent with the statements at https://ccs-specs.icpc.io/2023-06/contest_api#contest-state, which among other things say:
```
started:  Time when the contest actually started, or null if the contest has not started yet. 
frozen:  Time when the scoreboard was frozen, or null if the scoreboard has not been frozen.
ended: Time when the contest ended, or null if the contest has not ended. 
```
and so forth.

Of course, I suppose we _could_ define that **{}** has the semantic meaning "all fields of this object are, by definition, null".  But I'm not sure whether that would have ramifications elsewhere, and it just doesn't quite "feel right".

**Comment by nickygerritsen** [comment]
The [spec](https://ccs-specs.icpc.io/draft/contest_api#extensibility) says:

> In this specification and extensions, a property with value null may be left out by the server (i.e. not be present). A client must treat a property with value null equivalently as that property not being present.

So `{}` is semantically the same as setting everything to null.

We could of course be explicit here, but that does complicate the code (we would have to pre-create a state object).

**Comment by clevengr** [comment]
Hmm... I think I'd argue that "treating a property with value null equivalently as that property not being present" is, at best, ambiguous.  I'm not convinced that this clause explicitly means "if a property is missing, it is the same thing as that property existing and having a value of 'null' ".   Perhaps that was the intention, but I'm not convinced that's what it actually says.

But sure, we can define it that way.  It still means we should be returning "{ }" from a STATE endpoint before the contest starts, not returning "nothing".

**Comment by nickygerritsen** [comment]
We should discuss at the next CLICS meeting (which is probably in Luxor) if that is indeed what is meant, but that is what I remember.

Anyway, the PR for `{}` is already up, and waiting approval 😃
