### ISSUE TITLE
CDS seems to ignore null contest start time and pause button is broken

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#865]
At EUC the practice session was delayed by setting the `start_time` of the contest in DOMjudge to `null`. But the CDS did not honor this. I then tried manually pausing the countdown, but that also didn't work.

I will do some investigation to see if I can reproduce this locally.

**Comment by nickygerritsen** [comment]
Update: it only breaks if you have an upstream CCS.

It seems to have broken when doing the defaults storage: https://github.com/icpctools/icpctools/blob/9e88e8c654575f8ecd7cec3d16d641e0c2a77255/CDS/src/org/icpc/tools/cds/util/PlaybackContest.java#L423-L423

It overwrites the start time again with what is in the config folder, it seems.

**Comment by deboer-tim** [comment]
Fixed by #896.
