### ISSUE TITLE
Award comparison

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#9]
We're going to try using the /awards endpoint to confirm that the primary CCS, secondary CCS, and CDS all agree on awards (medals, regionals, etc) that will be given. Make sure there's a page on the CDS that'll allow you to do this just like the scoreboard comparison.

**Comment by niemela** [comment]
> I may do a separate award comparison page or a more general graphical comparison.

Do we still want to do this? Is it needed?

**Comment by deboer-tim** [comment]
Closing. Yeah, if it hasn't been critical or worked on in a couple years...
