### ISSUE TITLE
Issues from WF46/47 Luxor

### ISSUE THREAD

**Issue by deboer-tim** [icpctools/icpctools#933]
CDS:
- [ ] Needs support for reloading backups/photos after a contest starts.
- [ ] CDS invalid login errors are generic for security reasons, but maybe for usability we should differentiate between invalid user and password.
- [ ] Need to improve how we clear caches, both CDS and tools clients. More automatic token changes.
- [ ] A list of 'what's up, what's partially up', e.g. 'we expect backups but only 5 are there' or scan for working webcams.

Floor map generator
- [ ] Outputs empty state object, would be better not to save it.
- [ ] Would be nice to cross-compare with actual teams (e.g. auto-gen spares for teams that are removed).

Resolver
- [ ] Automatic cropping of photos?
- [ ] More/interesting transitions

Longer term:
- [x] Support for scoring contests.
- [ ] Is there a 'never sleep' setting on Windows that we can use instead of setting power mode/screensaver?
- [ ] Errors in log from standalone resolver
- [ ] More transitions, esp in resolver

**Comment by meisterT** [comment]
Judging by https://github.com/DOMjudge/domjudge/pull/2489 the CDS did not expose the time limit in all cases (perhaps it didn't know yet?), so we need to make it either in the spec optional or add it to the CDS.

**Comment by deboer-tim** [comment]
> Judging by [DOMjudge/domjudge#2489](https://github.com/DOMjudge/domjudge/pull/2489) the CDS did not expose the time limit in all cases (perhaps it didn't know yet?), so we need to make it either in the spec optional or add it to the CDS.

FWIW that was fixed the same day (for the next test): https://github.com/icpctools/icpctools/pull/887. A couple problems started using the new yaml limits/timeout property that I hadn't seen before, so they 'didn't have a time limit' until the CDS was configured to point to DOMjudge and picked them up from there.

**Comment by meisterT** [comment]
Ah, thanks :-)

**Comment by deboer-tim** [comment]
List moved to wiki.
