### ISSUE TITLE
Resolver doesn't run with --presenter when end_of_updates state event has been sent

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#958]
When there is a non-null `end_of_updates` `state` event, the resolver stops with you pass `--presenter`, see [here](https://github.com/icpctools/icpctools/blob/08e6c9552abfd1fc431d139444c6b3e3a4a8411c/Resolver/src/org/icpc/tools/resolver/Resolver.java#L484-L487).

Why? If I remove that block the resolver runs correctly.

As a sidenote, that block is also triggered when using a file as contest source, even though we check for an instance of `RESTContestSource`. So it seems disk contests are also `RESTContestSource`?

**Comment by nickygerritsen** [comment]
The `RESTContestSource` thing is because of [this line](https://github.com/icpctools/icpctools/blob/08e6c9552abfd1fc431d139444c6b3e3a4a8411c/ContestModel/src/org/icpc/tools/contest/model/feed/ContestSource.java#L93-L93). Changing it to a `DiskContestSource` breaks `--presenter` since it expects a CDS. And since we can't run without `--presenter` because of #959 we can't change that line until that is fixed.

**Comment by cubercsl** [comment]
> When there is a non-null `end_of_updates` `state` event, the resolver stops with you pass `--presenter`, see [here](https://github.com/icpctools/icpctools/blob/08e6c9552abfd1fc431d139444c6b3e3a4a8411c/Resolver/src/org/icpc/tools/resolver/Resolver.java#L484-L487).
> 
> Why? If I remove that block the resolver runs correctly.

So do you think in current release, the workaround for running resolver in standalone mode with a contest archive (without CDS) is passing `--presenter` and remove `end_of_updates` event in `state` event?

**Comment by niemela** [comment]
> So do you think in current release, the workaround for running resolver in standalone mode with a contest archive (without CDS) is passing `--presenter` and remove `end_of_updates` event in `state` event?

Yes, removing `end_of_updates` or setting it to `null` should work. This is how we ran it e.g. at this years NAC.
