### ISSUE TITLE
Add max score to problem for scoring contests, so we can calculate first to solve

### ISSUE THREAD

**Issue by nickygerritsen** [icpctools/icpctools#964]
When we add `max_score` to the problem, we can use it to correctly calculate the first to solve for scoring algorithms.

**Comment by deboer-tim** [comment]
What is the problem (pun intended) here? max_score is in the spec, and looks like it is implemented in Problem.java. If it wasn't in the feed for this particular contest that's not an ICPC Tools issue; if it was and there's a bug, there is not enough info here to be able to fix anything.

**Comment by nickygerritsen** [comment]
Ah yeah it's there, I just missed it. So we can improve the logic for the yellow boxes for scoring with it: once you get the max score you can't get higher.

**Comment by nickygerritsen** [comment]
I added this to PR #963 and tested it with @niemela his test feed.
