### ISSUE TITLE
Fix `--speed` for the resolver

### ISSUE THREAD

**Issue by niemela** [icpctools/icpctools#982]
The `--speed` option currently does nothing for the resolver, at least when combined with `--presenter` and not running against a CDS.

It is possible that it would work without `--presenter`, and this might be solved after #959 is fixed (?).

**Comment by niemela** [comment]
Running the resolver with `--help` says that the command is `--speed <speedFactor>` while the documentation says `--fast <speedFactor>`. 

Which one should it be? I think `--speed` is the better name.

**Comment by nickygerritsen** [comment]
Both should work but are broken. Fix incoming.
